# this is the build file for project 
# it is autogenerated by the xmake build system.
# do not edit by hand.

ifneq ($(VERBOSE),1)
VV=@
endif

CCACHE=/usr/bin/ccache
CU=/usr/bin/clang
CS=/usr/bin/dotnet
MM=/usr/bin/gcc
RC=/usr/bin/rustc
GC=/usr/bin/go
AS=/usr/bin/gcc
CC=/usr/bin/gcc
MXX=/usr/bin/g++
CXX=/usr/bin/g++
ZC=/usr/bin/zig

RCAR=/usr/bin/rustc
ZCAR=/usr/bin/zig
AR=/usr/bin/ar
GCAR=/usr/bin/go
RCSH=/usr/bin/rustc
ZCSH=/usr/bin/zig
CS=/usr/bin/dotnet
SH=/usr/bin/g++
RCLD=/usr/bin/rustc
ZCLD=/usr/bin/zig
LD=/usr/bin/g++
GCLD=/usr/bin/go

bfc_LD=/usr/bin/g++
bfc_CXX=/usr/bin/g++
bfc_CXX=/usr/bin/g++
bfc_CXX=/usr/bin/g++

bfc_CXXFLAGS=-O3 -std=c++23 -I build/.objs/bfc/linux/x86_64/release/include/cxx -include common.hpp -Iinclude -DDEBUG_ON=0 -DNDEBUG
bfc_CXXFLAGS=-O3 -std=c++23 -I build/.objs/bfc/linux/x86_64/release/include/cxx -include common.hpp -Iinclude -DDEBUG_ON=0 -DNDEBUG
bfc_CXXFLAGS=-O3 -std=c++23 -I build/.objs/bfc/linux/x86_64/release/include/cxx -include common.hpp -Iinclude -DDEBUG_ON=0 -DNDEBUG
bfc_LDFLAGS=-s

default:  bfc

all:  bfc

.PHONY: default all  bfc

bfc: build/linux/x86_64/release/bfc
build/linux/x86_64/release/bfc: build/.objs/bfc/linux/x86_64/release/src/main.cpp.o build/.objs/bfc/linux/x86_64/release/src/transpiler.cpp.o build/.objs/bfc/linux/x86_64/release/src/cli.cpp.o
	@echo linking.release bfc
	@mkdir -p build/linux/x86_64/release
	$(VV)$(bfc_LD) -o build/linux/x86_64/release/bfc build/.objs/bfc/linux/x86_64/release/src/main.cpp.o build/.objs/bfc/linux/x86_64/release/src/transpiler.cpp.o build/.objs/bfc/linux/x86_64/release/src/cli.cpp.o $(bfc_LDFLAGS)

build/.objs/bfc/linux/x86_64/release/src/main.cpp.o: src/main.cpp
	@echo ccache compiling.release src/main.cpp
	@mkdir -p build/.objs/bfc/linux/x86_64/release/src
	$(VV)$(bfc_CXX) -c $(bfc_CXXFLAGS) -o build/.objs/bfc/linux/x86_64/release/src/main.cpp.o src/main.cpp

build/.objs/bfc/linux/x86_64/release/src/transpiler.cpp.o: src/transpiler.cpp
	@echo ccache compiling.release src/transpiler.cpp
	@mkdir -p build/.objs/bfc/linux/x86_64/release/src
	$(VV)$(bfc_CXX) -c $(bfc_CXXFLAGS) -o build/.objs/bfc/linux/x86_64/release/src/transpiler.cpp.o src/transpiler.cpp

build/.objs/bfc/linux/x86_64/release/src/cli.cpp.o: src/cli.cpp
	@echo ccache compiling.release src/cli.cpp
	@mkdir -p build/.objs/bfc/linux/x86_64/release/src
	$(VV)$(bfc_CXX) -c $(bfc_CXXFLAGS) -o build/.objs/bfc/linux/x86_64/release/src/cli.cpp.o src/cli.cpp

clean:  clean_bfc

clean_bfc: 
	@rm -rf build/linux/x86_64/release/bfc
	@rm -rf build/linux/x86_64/release/bfc.sym
	@rm -rf build/.objs/bfc/linux/x86_64/release/src/main.cpp.o
	@rm -rf build/.objs/bfc/linux/x86_64/release/src/transpiler.cpp.o
	@rm -rf build/.objs/bfc/linux/x86_64/release/src/cli.cpp.o

