# this is the build file for project 
# it is autogenerated by the xmake build system.
# do not edit by hand.

ifneq ($(VERBOSE),1)
VV=@
endif

CCACHE=/usr/bin/ccache
ZC=/usr/bin/zig
CC=/usr/bin/gcc
AS=/usr/bin/gcc
CXX=/usr/bin/g++
MM=/usr/bin/gcc
GC=/usr/bin/go
MXX=/usr/bin/g++
CS=/usr/bin/dotnet
RC=/usr/bin/rustc
CU=/usr/bin/clang

LD=/usr/bin/g++
ZCLD=/usr/bin/zig
RCLD=/usr/bin/rustc
CS=/usr/bin/dotnet
GCLD=/usr/bin/go
AR=/usr/bin/ar
ZCAR=/usr/bin/zig
RCAR=/usr/bin/rustc
GCAR=/usr/bin/go
SH=/usr/bin/g++
ZCSH=/usr/bin/zig
RCSH=/usr/bin/rustc

bfc_LD=/usr/bin/g++
bfc_CXX=/usr/bin/g++
bfc_CXX=/usr/bin/g++
bfc_CXX=/usr/bin/g++

bfc_CXXFLAGS=-O0 -std=c++23 -I build/.objs/bfc/linux/x86_64/debug/include/cxx -include common.hpp -Iinclude
bfc_CXXFLAGS=-O0 -std=c++23 -I build/.objs/bfc/linux/x86_64/debug/include/cxx -include common.hpp -Iinclude
bfc_CXXFLAGS=-O0 -std=c++23 -I build/.objs/bfc/linux/x86_64/debug/include/cxx -include common.hpp -Iinclude
bfc_LDFLAGS=

default:  bfc

all:  bfc

.PHONY: default all  bfc

bfc: build/linux/x86_64/debug/bfc
build/linux/x86_64/debug/bfc: build/.objs/bfc/linux/x86_64/debug/src/main.cpp.o build/.objs/bfc/linux/x86_64/debug/src/transpiler.cpp.o build/.objs/bfc/linux/x86_64/debug/src/cli.cpp.o
	@echo linking.debug bfc
	@mkdir -p build/linux/x86_64/debug
	$(VV)$(bfc_LDFLAGS)$(bfc_LD) -o build/linux/x86_64/debug/bfc build/.objs/bfc/linux/x86_64/debug/src/main.cpp.o build/.objs/bfc/linux/x86_64/debug/src/transpiler.cpp.o build/.objs/bfc/linux/x86_64/debug/src/cli.cpp.o

build/.objs/bfc/linux/x86_64/debug/src/main.cpp.o: src/main.cpp
	@echo ccache compiling.debug src/main.cpp
	@mkdir -p build/.objs/bfc/linux/x86_64/debug/src
	$(VV)$(bfc_CXX) -c $(bfc_CXXFLAGS) -o build/.objs/bfc/linux/x86_64/debug/src/main.cpp.o src/main.cpp

build/.objs/bfc/linux/x86_64/debug/src/transpiler.cpp.o: src/transpiler.cpp
	@echo ccache compiling.debug src/transpiler.cpp
	@mkdir -p build/.objs/bfc/linux/x86_64/debug/src
	$(VV)$(bfc_CXX) -c $(bfc_CXXFLAGS) -o build/.objs/bfc/linux/x86_64/debug/src/transpiler.cpp.o src/transpiler.cpp

build/.objs/bfc/linux/x86_64/debug/src/cli.cpp.o: src/cli.cpp
	@echo ccache compiling.debug src/cli.cpp
	@mkdir -p build/.objs/bfc/linux/x86_64/debug/src
	$(VV)$(bfc_CXX) -c $(bfc_CXXFLAGS) -o build/.objs/bfc/linux/x86_64/debug/src/cli.cpp.o src/cli.cpp

clean:  clean_bfc

clean_bfc: 
	@rm -rf build/linux/x86_64/debug/bfc
	@rm -rf build/linux/x86_64/debug/bfc.sym
	@rm -rf build/.objs/bfc/linux/x86_64/debug/src/main.cpp.o
	@rm -rf build/.objs/bfc/linux/x86_64/debug/src/transpiler.cpp.o
	@rm -rf build/.objs/bfc/linux/x86_64/debug/src/cli.cpp.o

